# Generated by Django 4.2 on 2025-08-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_image_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='text_position',
            field=models.CharField(blank=True, choices=[('top', 'النص فوق الفيديو'), ('bottom', 'النص تحت الفيديو')], default='top', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='time_unit',
            field=models.CharField(choices=[('seconds', 'ثواني'), ('minutes', 'دقائق'), ('hours', 'ساعات')], default='minutes', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('text_video', 'Text + Video')], default='text', max_length=20),
        ),
    ]
