# Generated by Django 4.2 on 2025-08-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lesson_text_position_test_time_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attempt',
            name='review_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
