# Generated by Django 4.2 on 2025-08-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attempt_answers_attempt_review_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='review_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
