# Generated by Django 4.2 on 2025-08-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_test_review_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='review_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='review_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
