# Generated by Django 4.2 on 2025-08-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_attempt_review_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='إذا تم تحديده، سيتم إخفاء الدرس عن الطلاب.', verbose_name='إخفاء الدرس'),
        ),
    ]
