# Generated by Django 4.2 on 2025-08-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lesson_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='review_enabled',
        ),
        migrations.AddField(
            model_name='test',
            name='prevent_review',
            field=models.BooleanField(default=False, help_text='إذا تم تحديده، لن يتمكن الطالب من مراجعة إجاباته بعد انتهاء الاختبار.', verbose_name='منع مراجعة الاختبار'),
        ),
    ]
